receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  otelpartialreceiver:
    postgres: "postgres://postgres:test@otel-partial-collector-db:5432/otelpartialcollector?sslmode=disable"
    gc_interval: "5s"

exporters:
  debug:
  otelpartialexporter:
    postgres: "postgres://postgres:test@otel-partial-collector-db:5432/otelpartialcollector?sslmode=disable"
    expiry_factor: 3

processors:
  batch:
  groupbytrace:

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otelpartialexporter]
    traces:
      receivers: [otelpartialreceiver]
      processors: [groupbytrace]
      exporters: [debug]